# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  services.goxlr-utility.enable = true;
  environment.systemPackages = with pkgs; [goxlr-utility];
}
